name: CI

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: path/to/your/server/directory
        local-dir: path/to/your/local/directory
        # Optional, default is '.git*'
        exclude: '**/.well-known/**'